masters = gentoo
repo-name = zentoo
thin-manifests = true
sign-manifests = false
sign-commits = false
manifest-hashes = BLAKE2B SHA512
manifest-required-hashes = BLAKE2B
profile-formats = profile-set
cache-formats = md5-dict
