// Shared template for every note in the ~/research vault.
// Opt in from any note (paper review or grounded/ungrounded card) with:
//
//   #import "/.templates/note.typ": note-template
//   #show: note-template
//
// The template flows the note's body, then appends the paper library's
// bibliography (Hayagriva-style bib.yml, auto-regenerated by
// `papis export --format typst`). Change the style in ONE place to affect
// every note's preview / build output.
//
// Citation style: Taylor & Francis Harvard-X (the T&F/IJGIS house style).
// Other CSLs live in /.templates/csl/; swap the path below to change house
// style project-wide.

#let note-template(body) = {
  set quote(block: true, quotes: true)

  // Heading numbering must be ON for `@heading-label` to resolve inside a
  // single file (Typst refuses to reference unnumbered headings). Hide the
  // number visually so the vault reads like plain-text Zettelkasten cards,
  // not "1.2.3 Section"-numbered documents.
  set heading(numbering: "1.")
  show heading: it => text(weight: "bold", it.body)

  // Custom render for heading refs: link to the target using ONLY the
  // heading's body text — no "Section 1.2.3" prefix Typst adds by default.
  // NOTE: cross-file @refs don't resolve in Typst single-file compile;
  // this only affects within-file refs. Cross-card navigation happens in
  // nvim via zeta LSP.
  show ref: it => {
    if it.element != none and it.element.func() == heading {
      link(it.target, it.element.body)
    } else { it }
  }

  body
  pagebreak(weak: true)
  bibliography("/bib.yml", style: "/.templates/csl/taylor-and-francis-harvard-x.csl")
}

#let highlight-box(body) = block(
  width: 100%,
  radius: 4pt,
  inset: 10pt,
  fill: rgb("dddddd"),
  breakable: false,
  body,
)

#let source-link(target, label: "src") = align(right, text(
  font: "JetBrains Mono",
  size: 9pt,
  fill: luma(100),
  link(target)[#label],
))

// Back-link to a paper hub or other note. Same visual family as
// source-link. Signature is (target, body); zeta's query has a second
// #eq? rule for "back-link" so the target string is captured as a graph
// edge alongside plain #link.
#let back-link(target, body) = align(right, text(
  font: "JetBrains Mono",
  size: 9pt,
  fill: luma(100),
  link(target, body),
))

