#!/sbin/openrc-run
# Copyright 2026 Craig Miller
# Distributed under the terms of the GNU General Public License v2

name="kanata daemon"
description="kanata keyboard remapper"

command="/usr/bin/kanata"
command_args="--quiet --cfg /etc/kanata/kanata.kbd"
command_user="kanata:kanata"
supervisor="supervise-daemon"
respawn_delay=1
respawn_max=5
respawn_period=30

depend() {
    need localmount
    after udev modules
    before greetd
}
